#ifndef METRIC_GET_VERIFIER_H
#define METRIC_GET_VERIFIER_H

/* Generated by flatcc 0.4.3 FlatBuffers schema compiler for C by dvide.com */

#ifndef METRIC_GET_READER_H
#include "metric_get_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#define PDIAGNOSTIC_IGNORE_UNUSED
#include "flatcc/portable/pdiagnostic_push.h"

static int __metrics_MetricGetSeriesDataPoint_table_verifier(flatcc_table_verifier_descriptor_t *td);
static int __metrics_MetricGetSeriesData_table_verifier(flatcc_table_verifier_descriptor_t *td);
static int __metrics_MetricGetResult_table_verifier(flatcc_table_verifier_descriptor_t *td);

static int __metrics_MetricGetSeriesDataPoint_table_verifier(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* type */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* value */)) return ret;
    return flatcc_verify_ok;
}

static inline int metrics_MetricGetSeriesDataPoint_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, metrics_MetricGetSeriesDataPoint_identifier, &__metrics_MetricGetSeriesDataPoint_table_verifier);
}

static inline int metrics_MetricGetSeriesDataPoint_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, metrics_MetricGetSeriesDataPoint_type_identifier, &__metrics_MetricGetSeriesDataPoint_table_verifier);
}

static inline int metrics_MetricGetSeriesDataPoint_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__metrics_MetricGetSeriesDataPoint_table_verifier);
}

static inline int metrics_MetricGetSeriesDataPoint_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__metrics_MetricGetSeriesDataPoint_table_verifier);
}

static int __metrics_MetricGetSeriesData_table_verifier(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 1, 0, &__metrics_MetricGetSeriesDataPoint_table_verifier) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int metrics_MetricGetSeriesData_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, metrics_MetricGetSeriesData_identifier, &__metrics_MetricGetSeriesData_table_verifier);
}

static inline int metrics_MetricGetSeriesData_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, metrics_MetricGetSeriesData_type_identifier, &__metrics_MetricGetSeriesData_table_verifier);
}

static inline int metrics_MetricGetSeriesData_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__metrics_MetricGetSeriesData_table_verifier);
}

static inline int metrics_MetricGetSeriesData_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__metrics_MetricGetSeriesData_table_verifier);
}

static int __metrics_MetricGetResult_table_verifier(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* from_time */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* to_time */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* step */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 3, 0, &__metrics_MetricGetSeriesData_table_verifier) /* series */)) return ret;
    return flatcc_verify_ok;
}

static inline int metrics_MetricGetResult_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, metrics_MetricGetResult_identifier, &__metrics_MetricGetResult_table_verifier);
}

static inline int metrics_MetricGetResult_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, metrics_MetricGetResult_type_identifier, &__metrics_MetricGetResult_table_verifier);
}

static inline int metrics_MetricGetResult_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__metrics_MetricGetResult_table_verifier);
}

static inline int metrics_MetricGetResult_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__metrics_MetricGetResult_table_verifier);
}

#include "flatcc/portable/pdiagnostic_pop.h"
#endif /* METRIC_GET_VERIFIER_H */
