#ifndef METRIC_GET_READER_H
#define METRIC_GET_READER_H

/* Generated by flatcc 0.4.3 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#define PDIAGNOSTIC_IGNORE_UNUSED
#include "flatcc/portable/pdiagnostic_push.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct metrics_MetricGetSeriesDataPoint_table *metrics_MetricGetSeriesDataPoint_table_t;
typedef const flatbuffers_uoffset_t *metrics_MetricGetSeriesDataPoint_vec_t;
typedef flatbuffers_uoffset_t *metrics_MetricGetSeriesDataPoint_mutable_vec_t;
typedef const struct metrics_MetricGetSeriesData_table *metrics_MetricGetSeriesData_table_t;
typedef const flatbuffers_uoffset_t *metrics_MetricGetSeriesData_vec_t;
typedef flatbuffers_uoffset_t *metrics_MetricGetSeriesData_mutable_vec_t;
typedef const struct metrics_MetricGetResult_table *metrics_MetricGetResult_table_t;
typedef const flatbuffers_uoffset_t *metrics_MetricGetResult_vec_t;
typedef flatbuffers_uoffset_t *metrics_MetricGetResult_mutable_vec_t;



struct metrics_MetricGetSeriesDataPoint_table { uint8_t unused__; };

#ifndef metrics_MetricGetSeriesDataPoint_identifier
#define metrics_MetricGetSeriesDataPoint_identifier flatbuffers_identifier
#endif
#define metrics_MetricGetSeriesDataPoint_type_hash ((flatbuffers_thash_t)0x9f436231)
#define metrics_MetricGetSeriesDataPoint_type_identifier "\x31\x62\x43\x9f"
static inline size_t metrics_MetricGetSeriesDataPoint_vec_len(metrics_MetricGetSeriesDataPoint_vec_t vec)
__flatbuffers_vec_len(vec)
static inline metrics_MetricGetSeriesDataPoint_table_t metrics_MetricGetSeriesDataPoint_vec_at(metrics_MetricGetSeriesDataPoint_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(metrics_MetricGetSeriesDataPoint_table_t, vec, i, 0)
__flatbuffers_table_as_root(metrics_MetricGetSeriesDataPoint)

__flatbuffers_define_scalar_field(0, metrics_MetricGetSeriesDataPoint, type, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(1, metrics_MetricGetSeriesDataPoint, value, flatbuffers_double, double, 0.000000)

struct metrics_MetricGetSeriesData_table { uint8_t unused__; };

#ifndef metrics_MetricGetSeriesData_identifier
#define metrics_MetricGetSeriesData_identifier flatbuffers_identifier
#endif
#define metrics_MetricGetSeriesData_type_hash ((flatbuffers_thash_t)0x3e042ec5)
#define metrics_MetricGetSeriesData_type_identifier "\xc5\x2e\x04\x3e"
static inline size_t metrics_MetricGetSeriesData_vec_len(metrics_MetricGetSeriesData_vec_t vec)
__flatbuffers_vec_len(vec)
static inline metrics_MetricGetSeriesData_table_t metrics_MetricGetSeriesData_vec_at(metrics_MetricGetSeriesData_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(metrics_MetricGetSeriesData_table_t, vec, i, 0)
__flatbuffers_table_as_root(metrics_MetricGetSeriesData)

__flatbuffers_define_string_field(0, metrics_MetricGetSeriesData, name, 0)
__flatbuffers_define_vector_field(1, metrics_MetricGetSeriesData, data, metrics_MetricGetSeriesDataPoint_vec_t, 0)

struct metrics_MetricGetResult_table { uint8_t unused__; };

#ifndef metrics_MetricGetResult_identifier
#define metrics_MetricGetResult_identifier flatbuffers_identifier
#endif
#define metrics_MetricGetResult_type_hash ((flatbuffers_thash_t)0xd712fe81)
#define metrics_MetricGetResult_type_identifier "\x81\xfe\x12\xd7"
static inline size_t metrics_MetricGetResult_vec_len(metrics_MetricGetResult_vec_t vec)
__flatbuffers_vec_len(vec)
static inline metrics_MetricGetResult_table_t metrics_MetricGetResult_vec_at(metrics_MetricGetResult_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(metrics_MetricGetResult_table_t, vec, i, 0)
__flatbuffers_table_as_root(metrics_MetricGetResult)

__flatbuffers_define_scalar_field(0, metrics_MetricGetResult, from_time, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(1, metrics_MetricGetResult, to_time, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(2, metrics_MetricGetResult, step, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_vector_field(3, metrics_MetricGetResult, series, metrics_MetricGetSeriesData_vec_t, 0)

#include "flatcc/portable/pdiagnostic_pop.h"
#endif /* METRIC_GET_READER_H */
