#ifndef METRIC_FIND_VERIFIER_H
#define METRIC_FIND_VERIFIER_H

/* Generated by flatcc 0.4.3 FlatBuffers schema compiler for C by dvide.com */

#ifndef METRIC_FIND_READER_H
#include "metric_find_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#define PDIAGNOSTIC_IGNORE_UNUSED
#include "flatcc/portable/pdiagnostic_push.h"

static int __metrics_LeafData_table_verifier(flatcc_table_verifier_descriptor_t *td);
static int __metrics_MetricSearchResult_table_verifier(flatcc_table_verifier_descriptor_t *td);
static int __metrics_MetricSearchResultList_table_verifier(flatcc_table_verifier_descriptor_t *td);

static int __metrics_LeafData_table_verifier(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* uuid */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* check_name */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* metric_name */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* category */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 4, 0) /* egress_function */)) return ret;
    return flatcc_verify_ok;
}

static inline int metrics_LeafData_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, metrics_LeafData_identifier, &__metrics_LeafData_table_verifier);
}

static inline int metrics_LeafData_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, metrics_LeafData_type_identifier, &__metrics_LeafData_table_verifier);
}

static inline int metrics_LeafData_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__metrics_LeafData_table_verifier);
}

static inline int metrics_LeafData_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__metrics_LeafData_table_verifier);
}

static int __metrics_MetricSearchResult_table_verifier(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* leaf */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_table_field(td, 2, 0, &__metrics_LeafData_table_verifier) /* leaf_data */)) return ret;
    return flatcc_verify_ok;
}

static inline int metrics_MetricSearchResult_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, metrics_MetricSearchResult_identifier, &__metrics_MetricSearchResult_table_verifier);
}

static inline int metrics_MetricSearchResult_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, metrics_MetricSearchResult_type_identifier, &__metrics_MetricSearchResult_table_verifier);
}

static inline int metrics_MetricSearchResult_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__metrics_MetricSearchResult_table_verifier);
}

static inline int metrics_MetricSearchResult_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__metrics_MetricSearchResult_table_verifier);
}

static int __metrics_MetricSearchResultList_table_verifier(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &__metrics_MetricSearchResult_table_verifier) /* results */)) return ret;
    return flatcc_verify_ok;
}

static inline int metrics_MetricSearchResultList_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, metrics_MetricSearchResultList_identifier, &__metrics_MetricSearchResultList_table_verifier);
}

static inline int metrics_MetricSearchResultList_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, metrics_MetricSearchResultList_type_identifier, &__metrics_MetricSearchResultList_table_verifier);
}

static inline int metrics_MetricSearchResultList_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &__metrics_MetricSearchResultList_table_verifier);
}

static inline int metrics_MetricSearchResultList_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &__metrics_MetricSearchResultList_table_verifier);
}

#include "flatcc/portable/pdiagnostic_pop.h"
#endif /* METRIC_FIND_VERIFIER_H */
