# automatically generated by the FlatBuffers compiler, do not modify

# namespace: metrics

import flatbuffers

class MetricGetSeriesDataPoint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMetricGetSeriesDataPoint(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MetricGetSeriesDataPoint()
        x.Init(buf, n + offset)
        return x

    # MetricGetSeriesDataPoint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MetricGetSeriesDataPoint
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MetricGetSeriesDataPoint
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def MetricGetSeriesDataPointStart(builder): builder.StartObject(2)
def MetricGetSeriesDataPointAddType(builder, type): builder.PrependInt32Slot(0, type, 0)
def MetricGetSeriesDataPointAddValue(builder, value): builder.PrependFloat64Slot(1, value, 0.0)
def MetricGetSeriesDataPointEnd(builder): return builder.EndObject()
