# automatically generated by the FlatBuffers compiler, do not modify

# namespace: metrics

import flatbuffers

class MetricGetSeriesData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMetricGetSeriesData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MetricGetSeriesData()
        x.Init(buf, n + offset)
        return x

    # MetricGetSeriesData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MetricGetSeriesData
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # MetricGetSeriesData
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .MetricGetSeriesDataPoint import MetricGetSeriesDataPoint
            obj = MetricGetSeriesDataPoint()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MetricGetSeriesData
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0
    
    @staticmethod
    def MetricGetSeriesDataStart(builder): builder.StartObject(2)

    @staticmethod
    def MetricGetSeriesDataAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

    @staticmethod
    def MetricGetSeriesDataAddData(builder, data): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

    @staticmethod
    def MetricGetSeriesDataStartDataVector(builder, numElems): return builder.StartVector(4, numElems, 4)

    @staticmethod
    def MetricGetSeriesDataEnd(builder): return builder.EndObject()
